/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public void getGreeting() throws Exception {
        //TestCases tests = new TestCases(); // Initialize your test class

        //TODO: call your test case functions one after other here

       // tests.testCase01();

      //NestedFrames nf= new NestedFrames();
      // nf.NestedFramesTest();

      // SearchAmazon sa= new SearchAmazon();
      //sa.SearchAmazonTest();
      //hyperlinkscount linkscount= new hyperlinkscount();
     // linkscount.hyperlinkscountTest();

    // LinkedlnPost lp = new LinkedlnPost();
     
  //lp.LinkedLnpostcenario();
        
  // ImageURLBMS imageurl= new ImageURLBMS();
   //imageurl.ImageURLBMSTest();

   Imdbratings ir = new Imdbratings();
   ir.ImdbratingsTest();
   //END Tests
      //tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws Exception {
        new App().getGreeting();
    }
}
